"""approvals

Revision ID: 11b549bf94e9
Revises: 3994e814c739
Create Date: 2024-12-16 23:21:25.644620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b549bf94e9'
down_revision: Union[str, None] = '3994e814c739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('va_allocation_approval_matrix',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('va_forecast_detail_months_archive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=True),
    sa.Column('forecast_detail_id', sa.String(length=255), nullable=True),
    sa.Column('forecast_month', sa.Integer(), nullable=True),
    sa.Column('rs_gov', sa.Integer(), nullable=True),
    sa.Column('ws_gov', sa.Integer(), nullable=True),
    sa.Column('rs_priv', sa.Integer(), nullable=True),
    sa.Column('ws_priv', sa.Integer(), nullable=True),
    sa.Column('total_rs', sa.Integer(), nullable=True),
    sa.Column('prev_rs_gov', sa.Integer(), nullable=True),
    sa.Column('prev_rs_priv', sa.Integer(), nullable=True),
    sa.Column('total_prev_rs', sa.Integer(), nullable=True),
    sa.Column('total_ws', sa.Integer(), nullable=True),
    sa.Column('total_prev_final_conf_allocation', sa.Integer(), nullable=True),
    sa.Column('new_ws_req', sa.Integer(), nullable=True),
    sa.Column('hmsi_allocation', sa.Integer(), nullable=True),
    sa.Column('adjustment', sa.Integer(), nullable=True),
    sa.Column('confirmed_prev_final_ws_gov', sa.Integer(), nullable=True),
    sa.Column('confirmed_prev_final_ws_priv', sa.Integer(), nullable=True),
    sa.Column('confirmed_ws_gov', sa.Integer(), nullable=True),
    sa.Column('confirmed_ws_priv', sa.Integer(), nullable=True),
    sa.Column('confirmed_total_ws', sa.Integer(), nullable=True),
    sa.Column('confirmed_final_gov', sa.Integer(), nullable=True),
    sa.Column('confirmed_final_priv', sa.Integer(), nullable=True),
    sa.Column('confirmed_total_final_ws', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_forecast_details_archive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=True),
    sa.Column('forecast_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('end_stock', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_forecasts_archive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('dealer_id', sa.String(length=255), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), server_default='-', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_allocation_approvals',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_comment', sa.Text(), nullable=True),
    sa.Column('approval_flag', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', 'WAITING', 'REVISED', 'CLOSED', 'ACKNOWLEDGED', name='allocationapprovalflagenum'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['va_users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['va_users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['va_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['va_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('va_allocation_approvals')
    op.drop_table('va_users')
    op.drop_table('va_forecasts_archive')
    op.drop_table('va_forecast_details_archive')
    op.drop_table('va_forecast_detail_months_archive')
    op.drop_table('va_allocation_approval_matrix')
    # ### end Alembic commands ###
