"""init_migrations

Revision ID: 328e1ed50314
Revises: 
Create Date: 2024-11-18 18:34:08.513628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328e1ed50314'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('va_categories',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_dealers',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_slot_calculations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('forecast_order_cat_2', sa.Integer(), nullable=False),
    sa.Column('forecast_order_cat_3', sa.Integer(), nullable=False),
    sa.Column('urgent_order_cat_2', sa.Integer(), nullable=False),
    sa.Column('urgent_order_cat_3', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_stock_pilots',
    sa.Column('segment_id', sa.String(length=255), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('segment_id', 'month', 'year')
    )
    op.create_table('va_dealer_branches',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dealer_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['va_dealers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_dealer_forecast',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['va_dealers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_segments',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['va_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_models',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('segment_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['va_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_slot_calculation_stock_pilots',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('slot_calculation_id', sa.String(length=255), nullable=False),
    sa.Column('segment_id', sa.String(length=255), nullable=False),
    sa.Column('stock_pilot', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['va_segments.id'], ),
    sa.ForeignKeyConstraint(['slot_calculation_id'], ['va_slot_calculations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_dealer_forecast_model',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('dealer_forecast_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('dealer_end_stock', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['dealer_forecast_id'], ['va_dealer_forecast.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['va_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_slot_calculation_models',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('slot_calculation_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['va_models.id'], ),
    sa.ForeignKeyConstraint(['slot_calculation_id'], ['va_slot_calculations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_dealer_forecast_months',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('dealer_forecast_model_id', sa.String(length=255), nullable=False),
    sa.Column('forecast_month', sa.Integer(), nullable=False),
    sa.Column('rs_gov', sa.Integer(), nullable=False),
    sa.Column('rs_priv', sa.Integer(), nullable=False),
    sa.Column('total_rs', sa.Integer(), nullable=False),
    sa.Column('prev_rs_gov', sa.Integer(), nullable=False),
    sa.Column('prev_rs_priv', sa.Integer(), nullable=False),
    sa.Column('total_prev_rs', sa.Integer(), nullable=False),
    sa.Column('ws_gov', sa.Integer(), nullable=False),
    sa.Column('ws_priv', sa.Integer(), nullable=False),
    sa.Column('total_ws', sa.Integer(), nullable=False),
    sa.Column('prev_final_ws_gov_conf', sa.Integer(), nullable=False),
    sa.Column('prev_final_ws_priv_conf', sa.Integer(), nullable=False),
    sa.Column('prev_final_confirm_allocation', sa.Integer(), nullable=False),
    sa.Column('new_ws_req', sa.Integer(), nullable=False),
    sa.Column('hmsi_allocation', sa.Integer(), nullable=False),
    sa.Column('ws_gov_conf', sa.Integer(), nullable=False),
    sa.Column('ws_priv_conf', sa.Integer(), nullable=False),
    sa.Column('total_ws_conf', sa.Integer(), nullable=False),
    sa.Column('final_ws_gov_conf', sa.Integer(), nullable=False),
    sa.Column('final_ws_priv_conf', sa.Integer(), nullable=False),
    sa.Column('total_final_ws_conf', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['dealer_forecast_model_id'], ['va_dealer_forecast_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_slot_calculation_months',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('slot_calculation_model_id', sa.String(length=255), nullable=False),
    sa.Column('forecast_month', sa.Integer(), nullable=False),
    sa.Column('take_off', sa.Integer(), nullable=False),
    sa.Column('bo', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('stock_pilot', sa.Integer(), nullable=False),
    sa.Column('soa', sa.Integer(), nullable=False),
    sa.Column('oc', sa.Integer(), nullable=False),
    sa.Column('booking', sa.Integer(), nullable=False),
    sa.Column('forecast_order', sa.Integer(), nullable=False),
    sa.Column('urgent_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['slot_calculation_model_id'], ['va_slot_calculation_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    
    op.execute(
        """
        INSERT INTO va_categories (id, name)
        VALUES
        ('CATXID0012024AB', 'CAT2'),
        ('CATXID0022024BC', 'CAT3')
        """
    )

    op.execute(
        """
        INSERT INTO va_segments (id, name, category_id, percentage, month, year)
        VALUES
        ('SEGXID0012024XY', '4w Bus', 'CATXID0012024AB', 100, 1, 2024),
        ('SEGXID0022024YZ', '4w Truck', 'CATXID0012024AB', 100, 1, 2024),
        ('SEGXID0032024ZX', '6w Bus', 'CATXID0012024AB', 100, 1, 2024),
        ('SEGXID0042024XW', '6w Std', 'CATXID0012024AB', 100, 1, 2024),
        ('SEGXID0052024WY', '6w HD', 'CATXID0012024AB', 100, 1, 2024),

        ('SEGXID0062024VB', '4x2 (FG)', 'CATXID0022024BC', 100, 1, 2024),
        ('SEGXID0072024CV', '6x2 (FL)', 'CATXID0022024BC', 100, 1, 2024),
        ('SEGXID0082024BN', '6x4 (FM)', 'CATXID0022024BC', 100, 1, 2024),
        ('SEGXID0092024MK', 'TH', 'CATXID0022024BC', 100, 1, 2024),
        ('SEGXID0102024PL', 'Bus', 'CATXID0022024BC', 100, 1, 2024)
        """
    )

    op.execute(
        """
        INSERT INTO va_dealers (id, name)
        VALUES
        ('DEALXID0012024QA', 'IPNS'),
        ('DEALXID0022024WE', 'CMC'),
        ('DEALXID0032024RT', 'CKMN'),
        ('DEALXID0042024TY', 'MP Solo'),
        ('DEALXID0052024YU', 'DCM'),
        ('DEALXID0062024UI', 'KMS'),
        ('DEALXID0072024IO', 'KMSA'),
        ('DEALXID0082024OP', 'JIM')
        """
    )
    
    op.execute(
        """
        INSERT INTO va_models (id, name, segment_id) 
        VALUES
        ('MODXID0012024AB', '115SDB STD', 'SEGXID0012024XY'),
        ('MODXID0022024BC', '115 SDB FLEXICAB L', 'SEGXID0012024XY'),
        ('MODXID0032024CD', '115SDB L STD', 'SEGXID0012024XY'),
        ('MODXID0042024DE', '115SDBL PRIMECAB L', 'SEGXID0012024XY'),
        ('MODXID0052024EF', '115SD STD', 'SEGXID0012024XY'),
        ('MODXID0062024FG', '115SDR STD', 'SEGXID0012024XY'),
        ('MODXID0072024GH', '115SDL STD', 'SEGXID0012024XY'),
        ('MODXID0082024HI', '115LD STD', 'SEGXID0012024XY'),
        ('MODXID0092024IJ', '115HD STD', 'SEGXID0012024XY'),

        ('MODXID0102024JK', '136MD STD', 'SEGXID0022024YZ'),
        ('MODXID0112024KL', '136MDL STD', 'SEGXID0022024YZ'),
        ('MODXID0122024LM', '136MDB L STD', 'SEGXID0022024YZ'),

        ('MODXID0132024MN', '136HDL 6x2', 'SEGXID0032024ZX'),
        ('MODXID0142024NO', '136HDL 6.4', 'SEGXID0032024ZX'),
        ('MODXID0152024OP', '136HDL 4X4', 'SEGXID0032024ZX'),
        ('MODXID0162024PQ', '136HD 6.4', 'SEGXID0032024ZX'),
        ('MODXID0172024QR', '136HDX 5.8', 'SEGXID0032024ZX'),
        ('MODXID0182024RS', '136HDX 5.8 PTO', 'SEGXID0032024ZX'),
        ('MODXID0192024ST', '136HDX MIXER', 'SEGXID0032024ZX'),
        ('MODXID0202024TU', '136HD Plantation', 'SEGXID0032024ZX'),

        ('MODXID0212024UV', '136HD 6.8', 'SEGXID0042024XW'),
        ('MODXID0222024VW', '136HDX 6.8', 'SEGXID0042024XW'),
        ('MODXID0232024WX', '136HDX 6.8 PTO', 'SEGXID0042024XW'),
        ('MODXID0242024XY', '136HDX 4X4', 'SEGXID0042024XW'),
        ('MODXID0252024YZ', '136HDX LSD', 'SEGXID0042024XW'),
        ('MODXID0262024ZA', '136 HDX Plantation 5.8 PTO', 'SEGXID0042024XW'),

        ('MODXID0272024AB', 'GB150 5.1', 'SEGXID0052024WY'),
        ('MODXID0282024BC', 'GB150 5.5', 'SEGXID0052024WY'),
        ('MODXID0292024CD', 'GB150 AT 5.1', 'SEGXID0052024WY'),
        ('MODXID0302024DE', 'GB150 AT 5.8', 'SEGXID0052024WY'),
        ('MODXID0312024EF', 'GB150L 5.1', 'SEGXID0052024WY'),
        ('MODXID0322024FG', 'GB150L 5.5', 'SEGXID0052024WY'),
        ('MODXID0332024GH', 'GB150L AT 5.1', 'SEGXID0052024WY'),
        ('MODXID0342024HI', 'GB150L AT 5.8', 'SEGXID0052024WY'),

        ('MODXID0352024IJ', 'FG 260 TH', 'SEGXID0062024VB'),

        ('MODXID0362024JK', 'FG 260 JK', 'SEGXID0102024PL'),
        ('MODXID0372024KL', 'FG 260 JK ABS', 'SEGXID0102024PL'),
        ('MODXID0382024LM', 'FG 260 JL', 'SEGXID0102024PL'),
        ('MODXID0392024MN', 'FG 260 JP', 'SEGXID0102024PL'),
        ('MODXID0402024NO', 'FG 260 JS', 'SEGXID0102024PL'),
        ('MODXID0412024OP', 'FG 260 JU', 'SEGXID0102024PL'),
        ('MODXID0422024PQ', 'FG 260 JJ', 'SEGXID0102024PL'),
        ('MODXID0432024QR', 'FG 260 JM', 'SEGXID0102024PL'),
        ('MODXID0442024RS', 'FL 260 JN', 'SEGXID0102024PL'),
        ('MODXID0452024ST', 'FL 260 JN ABS', 'SEGXID0102024PL'),
        ('MODXID0462024TU', 'FL 260 JW (EIV)', 'SEGXID0102024PL'),
        ('MODXID0472024UV', 'FL 260 JW ABS', 'SEGXID0102024PL'),
        ('MODXID0482024VW', 'FL 280 JT', 'SEGXID0102024PL'),

        ('MODXID0492024WX', 'FMX 280 TH', 'SEGXID0072024CV'),
        ('MODXID0502024XY', 'FLE 260 JW', 'SEGXID0072024CV'),
        ('MODXID0512024YZ', 'FLX 280 JW', 'SEGXID0072024CV'),
        ('MODXID0522024ZA', 'FL 280 JW', 'SEGXID0072024CV'),
        ('MODXID0532024AB', 'FM 260 JD', 'SEGXID0072024CV'),
        ('MODXID0542024BC', 'FM 280 TH', 'SEGXID0072024CV'),
        ('MODXID0552024CD', 'FM 280 JM', 'SEGXID0072024CV'),
        ('MODXID0562024DE', 'FM 280 TH ABS', 'SEGXID0072024CV'),
        ('MODXID0572024EF', 'FM 280 JD', 'SEGXID0072024CV'),
        ('MODXID0582024FG', 'FM 280 JD ABS', 'SEGXID0072024CV'),
        ('MODXID0592024GH', 'FM 280 JD MINING', 'SEGXID0072024CV'),
        ('MODXID0602024HI', 'FM 280 JW', 'SEGXID0072024CV'),
        ('MODXID0612024IJ', 'FM 280 JL', 'SEGXID0072024CV'),

        ('MODXID0622024JK', 'FM 340 TH', 'SEGXID0082024BN'),
        ('MODXID0632024KL', 'FM 340 TH ABS', 'SEGXID0082024BN'),
        ('MODXID0642024LM', 'FM 340 PL MINING', 'SEGXID0082024BN'),
        ('MODXID0652024MN', 'FM 340 PD MINING', 'SEGXID0082024BN'),
        ('MODXID0662024NO', 'SG 280 TH', 'SEGXID0082024BN'),

        ('MODXID0672024OP', 'SG 280 TH ABS', 'SEGXID0092024MK'),
        ('MODXID0682024PQ', 'AK 240 STD', 'SEGXID0092024MK'),
        ('MODXID0692024QR', 'RK280 STD', 'SEGXID0092024MK'),
        ('MODXID0702024RS', 'RK280 ABS', 'SEGXID0092024MK'),
        ('MODXID0712024ST', 'RM 280', 'SEGXID0092024MK'),
        ('MODXID0722024TU', 'RM280 ABS', 'SEGXID0092024MK');
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('va_slot_calculation_months')
    op.drop_table('va_dealer_forecast_months')
    op.drop_table('va_slot_calculation_models')
    op.drop_table('va_dealer_forecast_model')
    op.drop_table('va_slot_calculation_stock_pilots')
    op.drop_table('va_models')
    op.drop_table('va_segments')
    op.drop_table('va_dealer_forecast')
    op.drop_table('va_dealer_branches')
    op.drop_table('va_stock_pilots')
    op.drop_table('va_slot_calculations')
    op.drop_table('va_dealers')
    op.drop_table('va_categories')
    # ### end Alembic commands ###
