"""update_segment_table

Revision ID: 88f79bb8a0d7
Revises: aab6bc0a44c3
Create Date: 2024-11-14 21:50:53.897665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88f79bb8a0d7'
down_revision: Union[str, None] = 'aab6bc0a44c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('va_segments', sa.Column('percentage', sa.Integer(), nullable=True))
    op.add_column('va_segments', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('va_segments', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('va_segments', 'year')
    op.drop_column('va_segments', 'month')
    op.drop_column('va_segments', 'percentage')
    # ### end Alembic commands ###
