"""add dealers created at

Revision ID: ccbc677c73a8
Revises: 1e37b8eefcec
Create Date: 2024-12-12 10:50:14.783079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccbc677c73a8'
down_revision: Union[str, None] = '1e37b8eefcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('va_dealers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('va_dealers', 'created_at')
    # ### end Alembic commands ###
