"""create_forecast_table

Revision ID: dcb7f4b2feda
Revises: 15c816305702
Create Date: 2024-11-05 17:16:36.557318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb7f4b2feda'
down_revision: Union[str, None] = '15c816305702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('va_dealer_forecast',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['va_dealers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_dealer_forecast_model',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('dealer_forecast_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('dealer_end_stock', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['dealer_forecast_id'], ['va_dealer_forecast.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['va_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_dealer_forecast_months',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('dealer_forecast_model_id', sa.String(length=255), nullable=False),
    sa.Column('forecast_month', sa.Integer(), nullable=False),
    sa.Column('rs_gov', sa.Integer(), nullable=False),
    sa.Column('rs_priv', sa.Integer(), nullable=False),
    sa.Column('total_rs', sa.Integer(), nullable=False),
    sa.Column('prev_rs_gov', sa.Integer(), nullable=False),
    sa.Column('prev_rs_priv', sa.Integer(), nullable=False),
    sa.Column('total_prev_rs', sa.Integer(), nullable=False),
    sa.Column('ws_gov', sa.Integer(), nullable=False),
    sa.Column('ws_priv', sa.Integer(), nullable=False),
    sa.Column('total_ws', sa.Integer(), nullable=False),
    sa.Column('prev_final_ws_gov_conf', sa.Integer(), nullable=False),
    sa.Column('prev_final_ws_priv_conf', sa.Integer(), nullable=False),
    sa.Column('prev_final_confirm_allocation', sa.Integer(), nullable=False),
    sa.Column('new_ws_req', sa.Integer(), nullable=False),
    sa.Column('hmsi_allocation', sa.Integer(), nullable=False),
    sa.Column('ws_gov_conf', sa.Integer(), nullable=False),
    sa.Column('ws_priv_conf', sa.Integer(), nullable=False),
    sa.Column('total_ws_conf', sa.Integer(), nullable=False),
    sa.Column('final_ws_gov_conf', sa.Integer(), nullable=False),
    sa.Column('final_ws_priv_conf', sa.Integer(), nullable=False),
    sa.Column('total_final_ws_conf', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deletable', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['dealer_forecast_model_id'], ['va_dealer_forecast_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('va_dealer_forecast_months')
    op.drop_table('va_dealer_forecast_model')
    op.drop_table('va_dealer_forecast')
    # ### end Alembic commands ###
