"""add_calculation_slot_column

Revision ID: ea1ad81e6860
Revises: 30c8018ac0a7
Create Date: 2024-12-17 23:11:48.434716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1ad81e6860'
down_revision: Union[str, None] = '30c8018ac0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('va_slot_calculation_details', sa.Column('slot_1', sa.Integer(), nullable=True))
    op.add_column('va_slot_calculation_details', sa.Column('slot_2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('va_slot_calculation_details', 'slot_2')
    op.drop_column('va_slot_calculation_details', 'slot_1')
    # ### end Alembic commands ###
