app:
  port: 8000
  name: his-vehicle-allocation-backend
  environment: local

database:
  vehicle_allocation:
    host: "localhost"
    port: 5432
    name: "vehicle_allocations"
    username: "postgres"
    password: "postgres"

gcs:
  private: "tl-his2-private"
  public: "tl-his2-public"

outbound:
  iam:
    base_url: "http://34.101.141.65/iam_api"
