from enum import Enum


class AllocationApprovalFlagEnum(Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    WAITING = "WAITING"
    REVISED = "REVISED"
    CLOSED = "CLOSED"
    ACKNOWLEDGED = "ACKNOWLEDGED"


class ApprovalStatusEnum(Enum):
    SUBMIT = "SUBMIT"
    DRAFT = "DRAFT"
    WAITING_APPROVAL = "WAITING APPROVAL"
    REVISED = "REVISED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    APPROVED = "APPROVED"
    CONFIRMED = "CONFIRMED"
    EXPIRED = "EXPIRED"
    CANCEL_ORDER = "CANCEL ORDER"
    WAITING_APPROVAL_SALES_AREA = "WAITING APPROVAL SALES AREA"
    WAITING_APPROVAL_PRICING_ADMIN = "WAITING APPROVAL PRICING ADMIN"
    WAITING_APPROVAL_PRICING_AND_PROFIT_DEPARTMEN_HEAD = (
        "WAITING APPROVAL PRICING AND PROFIT DEPARTMENT HEAD"
    )
    WAITING_APPROVAL_ASM_DIVISION_HEAD = "WAITING APPROVAL ASM DIVISION HEAD"
    WAITING_APPROVAL_DIRECTOR = "WAITING APPROVAL DIRECTOR"
    WAITING_APPROVAL_PRESIDENT_DIRECTOR = "WAITING APPROVAL PRESIDENT DIRECTOR"
    WAITING_DEALER_CONFIRMATION = "WAITING DEALER CONFIRMATION"


class AllocationSubmissionStatusEnum(Enum):
    SUBMIT = "SUBMIT"
    DRAFT = "DRAFT"
